feat: FindMinNodeOfSubtree 함수 구현
OSS-project1/INHA_OSAP_002_Upside_Down_Cake pull request #23
Opened 2023-12-13 13:45 UTC by haebyun

특정 노드의 서브트리 내에 가장 작은 키값을 가지는 노드를 찾는 함수 구현

2023-12-13 13:49 UTC, whatsgoodg requested changes
함수 기능을 보기 이전에, clang-format을 지키지 않은 코드인 것 같습니다.
다시 clang-format에 맞추어 구현해주시길 바랍니다.

2023-12-13 14:01 UTC, jsk267 approved these changes
FindMinNodeOfSubtree의 함수가 정상적으로 작동될 것으로 보입니다

2023-12-13 14:03 UTC, jsk267 commented
> FindMinNodeOfSubtree의 함수가 정상적으로 작동될 것으로 보입니다

2023-12-13 14:26 UTC, whatsgoodg requested changes
현재 commit message에 필요 없는 모듈이 보입니다.

2023-12-14 08:16 UTC, whatsgoodg approved these changes
기능성 이상 없어보입니다.
테스트 통과한 것 확인하였습니다.

2023-12-14 08:16 UTC, merged